settings:
 email: ddikman@gmail.com
sites:
 - name: Blocket
   url: http://www.blocket.se/bostad/uthyres/orebro?sort=&ss=&se=&ros=&roe=&bs=&be=&mre=&q=&q=&q=&is=1&save_search=1&l=0&md=th&f=p&f=c&f=b&m=97
   examine: '#item_list'
